name: network_communication
description: Network communication gateways.

version: 1.0.0
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  agora_rtc_engine: ^6.3.0
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  onesignal_flutter: ^5.1.4
  permission_handler: ^11.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  mockito: ^5.4.4
  test: ^1.24.9
